# Generated by Django 5.2.3 on 2026-01-18 04:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_no', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('password_salt_b64', models.CharField(max_length=64)),
                ('password_hash_b64', models.CharField(max_length=128)),
                ('password_iterations', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUserMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hackathon.appuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'phone'], name='hackathon_a_user_id_b12360_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'phone'), name='uniq_member_phone_per_team')],
            },
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='hackathon.appusermember')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='hackathon.appuser')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['user', 'expires_at'], name='hackathon_a_user_id_9809eb_idx'),
                    models.Index(fields=['member', 'expires_at'], name='hackathon_a_member__b32262_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to='hackathon.appusermember')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['identifier', 'expires_at'], name='hackathon_o_identif_9df67f_idx'),
                    models.Index(fields=['member', 'expires_at'], name='hackathon_o_member__3c5c05_idx'),
                    models.Index(fields=['expires_at'], name='hackathon_o_expires_3a37f9_idx'),
                ],
            },
        ),
    ]
